DNA = "ATGCGTACCGTA"
A=len(DNA)
count_A=DNA.count("A")
count_T=DNA.count("T")
count_G=DNA.count("G")
count_C=DNA.count("C")
G=DNA.find("ATG")
print("Length of DNA sequence is:",A)
print("Number of A: ",count_A)
print("Number of T: ",count_T)
print("Number of G: ",count_G)
print("Number of C: ",count_C)
print("Start count found: ",G)
print(DNA[0:3])
